# Generated by Django 4.1.3 on 2022-11-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="session_url",
        ),
        migrations.AlterField(
            model_name="payment",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowing.borrowing",
            ),
        ),
    ]
