# Generated by Django 4.1.3 on 2022-11-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
